apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
        - name: rest
          image: shandysiswandi/go-rest:0.3.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  selector:
    app: rest
  ports:
    - name: http
      protocol: TCP
      targetPort: 8080 # this port is run in pod
      port: 80 # this port is run for service
